apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
  labels:
    app: influxdb-jmeter
data:
  load_test: |
    #!/bin/bash
    #Usage: ./load_test "path to the test script in jmx format"
    # /jmeter/apache-jmeter-5.0/bin/jmeter -n -t $1 -Dserver.rmi.ssl.disable=true -R `getent ahostsv4 jmeter-worker-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`
    # bzt $1 -o execution.0.distributed=[`getent ahostsv4 jmeter-worker-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`];
    if [ "`echo $1 | tail -c 4`" == "jmx" ];
    then
      jmeter -n -t $1 -Dserver.rmi.ssl.disable=true -R `getent ahostsv4 jmeter-worker-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`;
    else
      bzt $1 -o execution.0.distributed=[`getent ahostsv4 jmeter-worker-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`];
    fi

    