apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-persistent-vol-claim
  labels:
    type: awsEBS
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      