apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-vol
  labels:
    type: awsEBS
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0ece706e114114642
    fsType: ext4
