apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-vol
  labels:
    type: awsEBS
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: <volume-id-for-Persistant-EBS>
    fsType: ext4
