apiVersion: v1
kind: Service
metadata:
  name: jmeter-grafana
  labels:
    app: jmeter-grafana
spec:
  ports:
    - port: 80
    #for node port
    # - port: 3000
      targetPort: 3000
  selector:
    app: jmeter-grafana
  #for AWS/cloud  
  type: LoadBalancer
  #for minikube
  # type: NodePort